export type ComponentSize = 'small' | 'default' | 'large'
export type ComponentType = 'default' | 'primary' | 'success' | 'warning' | 'danger' | 'info'
export type StatusType = 'primary' | 'success' | 'warning' | 'danger' | 'info'
export type Placement =
  | 'top'
  | 'top-start'
  | 'top-end'
  | 'bottom'
  | 'bottom-start'
  | 'bottom-end'
  | 'left'
  | 'left-start'
  | 'left-end'
  | 'right'
  | 'right-start'
  | 'right-end'
