// 在 tsconfig.json 的 compilerOptions.types 中加入 "momeng-ui/global"
// 即可获得全局注册组件的类型提示（Volar / vue-tsc）。
declare module 'vue' {
  export interface GlobalComponents {
    MoButton: (typeof import('momeng-ui'))['MoButton']
    MoButtonGroup: (typeof import('momeng-ui'))['MoButtonGroup']
    MoIcon: (typeof import('momeng-ui'))['MoIcon']
    MoText: (typeof import('momeng-ui'))['MoText']
    MoLink: (typeof import('momeng-ui'))['MoLink']
    MoDivider: (typeof import('momeng-ui'))['MoDivider']
    MoSpace: (typeof import('momeng-ui'))['MoSpace']
    MoRow: (typeof import('momeng-ui'))['MoRow']
    MoCol: (typeof import('momeng-ui'))['MoCol']
    MoSeal: (typeof import('momeng-ui'))['MoSeal']
    MoConfigProvider: (typeof import('momeng-ui'))['MoConfigProvider']
    MoInput: (typeof import('momeng-ui'))['MoInput']
    MoInputNumber: (typeof import('momeng-ui'))['MoInputNumber']
    MoCheckbox: (typeof import('momeng-ui'))['MoCheckbox']
    MoCheckboxGroup: (typeof import('momeng-ui'))['MoCheckboxGroup']
    MoRadio: (typeof import('momeng-ui'))['MoRadio']
    MoRadioGroup: (typeof import('momeng-ui'))['MoRadioGroup']
    MoSwitch: (typeof import('momeng-ui'))['MoSwitch']
    MoSlider: (typeof import('momeng-ui'))['MoSlider']
    MoRate: (typeof import('momeng-ui'))['MoRate']
    MoSelect: (typeof import('momeng-ui'))['MoSelect']
    MoOption: (typeof import('momeng-ui'))['MoOption']
    MoForm: (typeof import('momeng-ui'))['MoForm']
    MoFormItem: (typeof import('momeng-ui'))['MoFormItem']
    MoCard: (typeof import('momeng-ui'))['MoCard']
    MoTag: (typeof import('momeng-ui'))['MoTag']
    MoBadge: (typeof import('momeng-ui'))['MoBadge']
    MoAvatar: (typeof import('momeng-ui'))['MoAvatar']
    MoTooltip: (typeof import('momeng-ui'))['MoTooltip']
    MoPopover: (typeof import('momeng-ui'))['MoPopover']
    MoCollapse: (typeof import('momeng-ui'))['MoCollapse']
    MoCollapseItem: (typeof import('momeng-ui'))['MoCollapseItem']
    MoTabs: (typeof import('momeng-ui'))['MoTabs']
    MoTabPane: (typeof import('momeng-ui'))['MoTabPane']
    MoTimeline: (typeof import('momeng-ui'))['MoTimeline']
    MoTimelineItem: (typeof import('momeng-ui'))['MoTimelineItem']
    MoTable: (typeof import('momeng-ui'))['MoTable']
    MoPagination: (typeof import('momeng-ui'))['MoPagination']
    MoProgress: (typeof import('momeng-ui'))['MoProgress']
    MoEmpty: (typeof import('momeng-ui'))['MoEmpty']
    MoSkeleton: (typeof import('momeng-ui'))['MoSkeleton']
    MoScroll: (typeof import('momeng-ui'))['MoScroll']
    MoMascot: (typeof import('momeng-ui'))['MoMascot']
    MoAlert: (typeof import('momeng-ui'))['MoAlert']
    MoDialog: (typeof import('momeng-ui'))['MoDialog']
    MoDrawer: (typeof import('momeng-ui'))['MoDrawer']
    MoLoading: (typeof import('momeng-ui'))['MoLoading']
    MoBreadcrumb: (typeof import('momeng-ui'))['MoBreadcrumb']
    MoBreadcrumbItem: (typeof import('momeng-ui'))['MoBreadcrumbItem']
    MoSteps: (typeof import('momeng-ui'))['MoSteps']
    MoStep: (typeof import('momeng-ui'))['MoStep']
    MoDropdown: (typeof import('momeng-ui'))['MoDropdown']
    MoDropdownItem: (typeof import('momeng-ui'))['MoDropdownItem']
    MoMenu: (typeof import('momeng-ui'))['MoMenu']
    MoMenuItem: (typeof import('momeng-ui'))['MoMenuItem']
    MoBacktop: (typeof import('momeng-ui'))['MoBacktop']
  }
  export interface ComponentCustomProperties {
    $message: (typeof import('momeng-ui'))['MoMessage']
    $notify: (typeof import('momeng-ui'))['MoNotification']
    vLoading: (typeof import('momeng-ui'))['vLoading']
  }
}
export {}
